service: power

frameworkVersion: '2'

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  profile: power
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT, '5432'}
    DB_USER: ${env:DB_USER}
    USERPOOL_ID: ${env:USERPOOL_ID}
    APP_BACKEND_CLIENT: ${env:APP_BACKEND_CLIENT}
    USERPOOL_NAME: ${env:USERPOOL_NAME}
    APP_BACKEND_CLIENT_NAME: ${env:APP_BACKEND_CLIENT_NAME}
  httpApi:
    payload: '1.0'
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:provider.environment.USERPOOL_ID}
        audience:
          - ${self:provider.environment.APP_BACKEND_CLIENT}

  iamRoleStatements:
    - Effect: 'Allow'
      Resource: '*'
      Action:
        - 's3:*'
        - 'cognito-idp:*'
plugins:
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-webpack
  - serverless-offline

functions:
  app:
    handler: apps/app/src/handler.default
    events:
      - httpApi:
          method: GET
          path: /graphql
          cors: true
      - httpApi:
          method: POST
          path: /graphql
          cors: true
  auth:
    handler: apps/app/src/authHandler.default
    events:
      - httpApi:
          method: GET
          path: /auth
          cors: true
          authorizer:
            name: serviceAuthorizer
      - httpApi:
          method: POST
          path: /auth
          cors: true
          authorizer:
            name: serviceAuthorizer
  cms:
    handler: apps/cms/src/handler.default
    events:
      - httpApi:
          method: GET
          path: /cms
      - httpApi:
          method: POST
          path: /cms

# resources:
#   Resources:
#     CognitoAuthorizer:
#       Type: AWS::ApiGatewayV2::Authorizer
#       Properties:
#         Name: ${self:service}-${self:provider.stage}-authorizer
#         AuthorizerType: JWT
#         IdentitySource:
#           - $request.header.Authorization
#         JwtConfiguration:
#           Audience:
#             - Ref: ${env.APP_BACKEND_CLIENT_NAME}
#           Issuer:
#             Fn::Join:
#               - ''
#               - - 'https://cognito-idp.'
#                 - '${opt:region, self:provider.region}'
#                 - '.amazonaws.com/'
#                 - Ref: '${env.USERPOOL_NAME}'

custom:
  serverless-offline:
    allowCache: true
    noPrependStageInUrl: true
  webpack:
    includeModules:
      # Include dynamically imported modules
      forceInclude:
        - 'pg'
        - 'apollo-server-express'
        - '@nestjs/platform-express'
        - 'class-validator'
        - 'class-transformer'
      forceExclude:
        - aws-sdk # available in lambda env by default
    packager: npm
